### ISSUE TITLE
example not showing the floorplan 

### ISSUE THREAD

**Issue by GhadahAlnasser** [IndoorAtlas/android-sdk-examples#104]
i added the API keys in properties and in manifast, in google maps overlay example i can see the google maps working properly but the floor plan i added in indooratlas not showing

**Comment by matti-ida** [comment]
Hi,

for general support please use our support portal at https://indooratlas.freshdesk.com/support/home
Troubleshooting check list is at https://indooratlas.freshdesk.com/support/solutions/folders/36000173652

Thanks.

- Matti
