### ISSUE TITLE
Example, not working at all

### ISSUE THREAD

**Issue by Nohemica** [IndoorAtlas/android-sdk-examples#11]
Hi, 
 I've used mapCreator and the mapping went well, I'm trying to make this example function with the map I uploaded, I used the Apy key and secret given to me but it won't work, is stays on: [000.82]: onStatusChanged: Available and nothing else.
 The Image view and Location Sharing stays blank.

**Comment by jraanamo** [comment]
Hi, 
After you did the mapping, did you try positioning with MapCreator application, were you able to get positions using that app?

**Comment by ntorppa** [comment]
Hi,
Also, make sure that you have added right credentials (api key and secred) into the gradle.properties and uncommented the lines.

If still no success even though positioning in MapCreator app works, please could you contact our customer support for deeper analysis!

Thanks!

**Comment by Nohemica** [comment]
Yes, the positioning worked fine, the api key and secret are correct and of curse I uncommented the lines (a little bit ofended) but still nothing happens.

**Comment by ntorppa** [comment]
Hi Nohemica,

Could you provide information about which device model and OS version you are using.

Thanks!

**Comment by scorpionmaher** [comment]
hello guys 
i want to know where i can find the credentials key please ??

**Comment by jraanamo** [comment]
Hi @scorpionmaher ,

You can create applications and api keys by logging into https://app.indooratlas.com/login.  

- On the left hand side menu select "My Apps". 
- Top right, you have blue button "Create new application"
- Once new app is created, hit "Add new api key" from top right
- Create the api key and configure you app

You can find the above and more in: http://docs.indooratlas.com/android/getting-started.html

-jukka-
