### ISSUE TITLE
Irrespective Movement of Blue Dot Location 

### ISSUE THREAD

**Issue by KathirveluM** [IndoorAtlas/android-sdk-examples#13]
Hi,
We are working with our uploaded Floor Design with this sample by mapping the Product & Secret Key in Indoor atlas. 

But we are facing issue as 
1. Irrespective Movement of Blue Dot in the location mapping even we are placing the Device on the table.
2. Most times its not navigating in the mapped coverage Area instead shows outside the waypoint mapped locations. 

Thanks in advance and awaiting for your response.

**Comment by elinapel** [comment]
Hi,

Usually these issues are related to the mapping phase of the venue, let's continue the discussion in our support channel (support@indooratlas.com or chat from the website) as we can't discuss your venue information here. Thanks!
