### ISSUE TITLE
IALocationListener never call onLocationChanged

### ISSUE THREAD

**Issue by rbermudez** [IndoorAtlas/android-sdk-examples#18]
Hi,

I have a problem with listener IALocationListener, the method onLocationChanged never execute but onStatusChanged is called every certain time, with this values:

log:onStatusChanged provider: IndoorAtlas status: 2 extras : null
log onStatusChanged provider: IndoorAtlas status: 11 extras :Bundle[{quality=0}]
log: onStatusChanged provider: IndoorAtlas status: 11 extras :Bundle[{quality=0}]
log: onStatusChanged provider: IndoorAtlas status: 11 extras :Bundle[{quality=0}]

Status 2  =  STATUS_AVAILABLE
Status 11 = STATUS_CALIBRATION_CHANGED(This status is not updated over, http://docs.indooratlas.com/)

The values 11 only appears in log if i move the device.

for this sample I follow the instructions of this video:
https://www.youtube.com/watch?v=2EXkV4xL5rg

Can you help to solve this problem, thanks.

**Comment by tonimakkonen** [comment]
Hi

Did positioning work using MapCreator 2 on your mobile device? This is the application you used to map the location.

**Comment by jraanamo** [comment]
The MapCreator2 and SDK Examples use the very same SDK that you can integrate as a developer. If you are able to get location on these two then there is a configuration or code issue with your integration. Please follow the example code and the documentation carefully to trace what is different with your project.
