### ISSUE TITLE
Not returning any data from my floorPlanId

### ISSUE THREAD

**Issue by Rainman85** [IndoorAtlas/android-sdk-examples#19]
final IALocation location = IALocation.from(IARegion.floorPlan(floorPlanId)); is returning zero values.

Also, it retrieves a map that i deleted previously from my locations. Is it not deleted from the cloud after I delete from My locations on your website? 

I have deleted all of my locations now on your website and it still retrieves the same location i first deleted. I don't have any locations how is it still retrieving them??

**Comment by tonimakkonen** [comment]
Hi

It will take some time before deleting a location has affect on positioning. Are you still having this issue? Also, what do you mean by returning zero values?
