### ISSUE TITLE
onLocationChanged does not execute

### ISSUE THREAD

**Issue by kristofferkarlsson93** [IndoorAtlas/android-sdk-examples#27]
Hi! 
I have done exactly as in the tutorial on the IndorAtlas webpage http://docs.indooratlas.com/android/dev-guide/getting-user-location.html except for the permission-asking, since the device Iam using is a Galaxy S4 with ANdroid 5.1. 

I do not get any print outs from the onLocationChanged handeler. But onStatusChanged is triggered every time I move the phone.

Do you have any Idea what the problem might be? 

`package com.karlssonkristoffer.indooratlastest2;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.widget.TextView;

import com.indooratlas.android.sdk.IALocation;
import com.indooratlas.android.sdk.IALocationListener;
import com.indooratlas.android.sdk.IALocationManager;
import com.indooratlas.android.sdk.IALocationRequest;

public class MainActivity extends AppCompatActivity {
    private static final String TAG = "message";

    IALocationManager myManager;
    private IALocationListener myListener = new IALocationListener() {
        @Override
        public void onLocationChanged(IALocation iaLocation) {
            //This function does not executes
            TextView text = (TextView) findViewById(R.id.textView);
            Log.d(TAG , "Latitude" + iaLocation.getLatitude());
            Log.d(TAG, "Longitude" + iaLocation.getLongitude());
        }

        @Override
        public void onStatusChanged(String s, int i, Bundle bundle) {
            //This executes
            Log.d(TAG, "Status changed");
            Log.d(TAG, s);
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        myManager = IALocationManager.create(this);
        Log.d(TAG, "created");
    }
    @Override
    protected void onResume(){
        super.onResume();
        myManager.requestLocationUpdates(IALocationRequest.create(), myListener);
        Log.d(TAG, "resume");
    }
    @Override
    protected void onPause() {
        super.onPause();
        myManager.removeLocationUpdates(myListener);
        Log.d(TAG, "paus");
    }

    @Override
    protected void onDestroy() {
        myManager.destroy();
        super.onDestroy();
        Log.d(TAG, "destroy");
    }
}`

**Comment by kristofferkarlsson93** [comment]
Alright, I just solved this. 
Using a older "dependencie-thingy" made the trick. 

Like this; dependencies {
compile 'com.indooratlas.android:indooratlas-android-sdk:2.0.2-beta@aar'
}

**Comment by tonimakkonen** [comment]
Hi

You should be able to get location with all publicly available SDKs. Did you remember the permissions in the manifest? Did you map the location first?

**Comment by WilkinsLiu** [comment]
Hi,
I 've got the same problem with sdk version 2.5.which version did you use when getting this problem?

**Comment by kristofferkarlsson93** [comment]
Hi! I do not remember actually. But it was the version that was specified on indorAtlas webpage, and used in their examples. Probably it was the 2.5.

**Comment by jraanamo** [comment]
All, 

onLocationChanged not getting executed has **always** been caused by a configuration or a mapping problem. There has never been a version where returning locations has not worked. Please verify first that you are able to get position updates using the _Test positioning_ feature of [MapCreator 2](https://play.google.com/store/apps/details?id=com.indooratlas.android.apps.jaywalker). We are working on material which will make getting started with our platform easier and less error prone.

Thanks!
