### ISSUE TITLE
[New feature] Way-Finding Example

### ISSUE THREAD

**Issue by lenguyenthanh** [IndoorAtlas/android-sdk-examples#28]
I see that IndoorAtlas has Way-Finding Use-case, but I couldn't find how to do it. Could you provide Way-Finding example in this repository.

**Comment by lenguyenthanh** [comment]
oh, may be I miss understand this feature. Does Way-Finding is similar with Navigation? And does IndoorAtlas support navigation between two locations?

**Comment by jraanamo** [comment]
Hi,

Currently the features with dotted line are such which can be implemented on top of the blue dot -feature but are not yet provided by IndoorAtlas' services.
