### ISSUE TITLE
setLocation not working

### ISSUE THREAD

**Issue by krunal3kapadiya** [IndoorAtlas/android-sdk-examples#33]
I have used mIALocationManager.setLocation(location), three times and app is displaying only one location. 

I also want to know the waypoints lat-lang that I generated from the [app](https://play.google.com/store/apps/details?id=com.indooratlas.android.apps.jaywalker) and draw the paths.

I also want the list of waypoints that I have stored.

**Comment by jraanamo** [comment]
Note that setLocation -method is only intended for special cases where you have an external source of information that you wish to input into IndoorAtlas as a "starting point" for the positioning session.

Unfortunately we don't currently support an API for fetching waypoints.

**Comment by krunal3kapadiya** [comment]
As per the [link](http://www.indooratlas.com/use-cases/), it provides wayfinding and multi-position, but you say that it does not provide any API for it. Then what is the use of this IndoorAtlas?

**Comment by jraanamo** [comment]
Waypoints are a technical concept used during the mapping phase - they are not related to wayfinding. Also, IndoorAtlas provides the foundational layer, the blue dot, on top of which e.g. wayfinding and multi-dot functionality can be built on. Those services are usually built by our customers or partners themselves.

**Comment by krunal3kapadiya** [comment]
How can I use that wayfinding and multi-dot functionality? What the steps I do have to follow?
I have successfully created Indoor map and implemented waypoints and wayfinding paths. Now, these problems are coming when I implement in my own application using this SDK.

**Comment by jraanamo** [comment]
IndoorAtlas **does not** provide wayfinding or multi-dot. For that you need to use third party libraries or develop this functionality yourself. For one approach on implementing multi-dot functionality see this simple example: https://github.com/IndoorAtlas/android-sdk-examples/tree/master/Basic/src/main/java/com/indooratlas/android/sdk/examples/sharelocation.
