### ISSUE TITLE
Providing non-indoor location updates.

### ISSUE THREAD

**Issue by deviousgeek** [IndoorAtlas/android-sdk-examples#39]
I couldn't glean this from the documentation, but does the SDK also provide (normal / regular) GPS updates when not in a mapped / serviced IndoorAtlas location? I have an app that transitions between an outdoor map and allows you to view an indoor are (calibrated with IndoorAtlas).

Can I swap out my existing location API with IALocationManager and expect it to work in the same way, with just finer details in the mapped location; or will I have to set up two location managers and switch one on when I am viewing the indoor map?

Thanks in advance!

**Comment by jraanamo** [comment]
Short answer is no. You cannot replace using platform location services (GPS, Network) with IndoorAtlas' service. You will need to keep reading GPS outdoors. When you are reading GPS outdoors and you are approaching an indoor mapped venue, IndoorAtlas' SDK will echo those GPS locations back via it's API callbacks and then transition to providing pure indoor locations once indoors. 

To implement indoor/outdoor with IndoorAtlas: 

- The service will first trigger an enter event into a region of type venue some time before actually walking in. While still reading GPS, you can start using locations from IndoorAtlas SDK. Do not yet assume that user is inside.
- The service will then trigger an enter event into a region of type floor plan. You can consider that user is now indoors and switch from outdoor view into indoor view.

To go from indoor to outdoor you need to consider an exit event from a region of type floor plan which is not closely followed by another entry into region of type floor plan (floor change) as a sign of user moving to outdoors. You can now switch from indoor view into outdoor view. 

For good indoor/outdoor detection it is also recommended that you keep reading GPS while indoors.

**Comment by deviousgeek** [comment]
Thanks for the help!
