### ISSUE TITLE
.getMap() no longer working

### ISSUE THREAD

**Issue by mlyhoops** [IndoorAtlas/android-sdk-examples#46]
I'm having a problem with the wayfinding file. the method getMap() no longer works with the updated google play services (which I need to implement firebase) and I'm wondering if you guys know a fix. I try to use the getMapAsync() but it just messes everything up because it returns void instead of GoogleMap

**Comment by vatolvan** [comment]
Hi @mlyhoops 

Here is quite good tutorial on how to update to getMapAsync: https://maps-apis.googleblog.com/2016/06/marker-zindex-and-more-come-to-google.html

Basically what you want to do is to run your code only after onMapReady() callback is called in your activity/fragment. That ensures that you have the map instance available.

```android
@Override
public void onMapReady(GoogleMap map) {
    mMap = map;
    doStuff();
}
```

**Comment by cocobino** [comment]
@Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        mapView = (MapView) view.findViewById(R.id.mapView);
        mapView.getMapAsync(this);
