### ISSUE TITLE
Unable to run sdk in a bound service

### ISSUE THREAD

**Issue by ritikrishu** [IndoorAtlas/android-sdk-examples#48]
Hi, I am trying to start atlas SDK in a bound service but only `onStatusChanged` callback is being called with following params-
* provider -> `IndoorAtlas`
* status -> `IALocationManager.STATUS_TEMPORARILY_UNAVAILABLE`

`onEnterRegion` or `onLocationChanged` are never called.
I've a minimal setup here - https://github.com/ritikrishu/AtlasOnBackgroundService

**Other notes:**
here is the implementation -> https://github.com/ritikrishu/AtlasOnBackgroundService/blob/master/app/src/main/java/com/ritikrishu/atlas/LocalService.java

in order to run, you need edit floor plan id, API key, and secret here -
https://github.com/ritikrishu/AtlasOnBackgroundService/blob/master/app/src/main/java/com/ritikrishu/atlas/LocalService.java#L52
https://github.com/ritikrishu/AtlasOnBackgroundService/blob/master/app/src/main/AndroidManifest.xml#L35-L38

logs that I am getting from this setup-
```
D/SGATLAS: Provider changed to -> IndoorAtlas
D/SGATLAS: Atlas service status received -> Location service temporarily unavailable. This could be due to no network connectivity.
```

**Comment by ritikrishu** [comment]
after waiting for some time got these logs as well
```
04-16 14:09:20.290 27630-27630/com.ritikrishu.atlas D/SGATLAS: Atlas service status received -> Location service is running but with limited accuracy and functionality.
04-16 14:09:24.067 27630-27630/com.ritikrishu.atlas D/SGATLAS: Provider changed to -> IndoorAtlas
04-16 14:09:24.068 27630-27630/com.ritikrishu.atlas D/SGATLAS: Atlas service status received -> Location service running normally.
```
but still no location or region related callbacks

**Comment by vatolvan** [comment]
Hi @ritikrishu 

I tried your example and it worked for me. Few notes:

- You don't really need to set the explicit location here: https://github.com/ritikrishu/AtlasOnBackgroundService/blob/master/app/src/main/java/com/ritikrishu/atlas/LocalService.java#L52, our system detects the correct floorplan automatically and you will get the region events to the RegionListener.
- You need to map a venue before trying to position: https://docs.indooratlas.com/map

**Comment by ritikrishu** [comment]
I see, I'll retry this.
Thanks for looking into it!
Closing this issue for now, will reopen if something goes wrong.
