### ISSUE TITLE
onLocationChanged wasn't called

### ISSUE THREAD

**Issue by lhphong09t2** [IndoorAtlas/android-sdk-examples#5]
Hi,
I enabled GPS and it works well with your app on Play store. But, with the example, we cannot get event onLocationChanged() although the onStatusChanged returns  status 0.

**Comment by jraanamo** [comment]
Please check that you have configured your credentials correctly as instructed here: https://github.com/IndoorAtlas/android-sdk-examples. Status 0 (zero) means "out of service". Please check also possible constant values STAUS_XXX at: http://docs.indooratlas.com/android/2.1.0/com/indooratlas/android/sdk/IALocationManager.html.

**Comment by lhphong09t2** [comment]
Thanks for responsing quickly. Now, onStatusChanged return 2 and then 11. Nothing happens in onLocationChanged. I configured as your instructions. More, iOS example works well.
![image](https://cloud.githubusercontent.com/assets/15918549/15008606/a3eb03c2-120b-11e6-9d86-66234d34815e.png)

**Comment by jraanamo** [comment]
First: you should not include credentials in these conversations. And secondly, is that a real device you are testing with or an emulator/simulator?

**Comment by lhphong09t2** [comment]
Thank. Don't worry because i will renew it later. I used a real device. This is strange. I tried to write with Google LocationManager and it returned location quickly. I understand you used ACCESS_COARSE_LOCATION permission in library and add more ACCESS_FINE_LOCATION to the example. The IndoorAtlas from Play store returned my location (as marker) after 1 -> 5 second(s).

**Comment by lhphong09t2** [comment]
Hi, 
I see in the tutorial for iOS, we put floor plan id but we don't with android.
![image](https://cloud.githubusercontent.com/assets/15918549/15033942/901b45a2-129a-11e6-9281-aa47ba089bd5.png)

**Comment by jraanamo** [comment]
Setting floor plan id in iOS is currently required since Wifi scanning is not available. With Android you don't need to set floor plan id as long as SDK can scan Wifi. On < Android 6.0 devices this means Wifi being enabled or background scanning being enabled. On Android 6.0 devices this means that location services are turned on and user has granted application permission to access location information.

**Comment by lhphong09t2** [comment]
Thanks, I tried to use Google LocationManager with ACCESS_COARSE_LOCATION permission (NETWORK_PROVIDER) and it returned my location correctly, but not to your. This is my MainActivity:

  `public class MainActivity extends AppCompatActivity implements LocationListener {

    private static final String TAG = "MainActivity";

    private IALocationManager mIALocationManager;
    //private LocationManager mLocationManager;

    private TextView _result;

    public void onRequest(View v) {
        mIALocationManager.requestLocationUpdates(IALocationRequest.create(), mIALocationListener);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        _result = (TextView) findViewById(R.id.result);
        mIALocationManager = IALocationManager.create(this);
        //mLocationManager = (LocationManager) getSystemService(LOCATION_SERVICE);
    }

    @Override
    protected void onResume() {
        super.onResume();

        mIALocationManager.requestLocationUpdates(IALocationRequest.create(), mIALocationListener);
        //mLocationManager.requestLocationUpdates(LocationManager.NETWORK_PROVIDER, 0, 0, this);
    }

    @Override
    protected void onPause() {
        super.onPause();

        mIALocationManager.removeLocationUpdates(mIALocationListener);
        //mLocationManager.removeUpdates(this);
    }

    @Override
    protected void onDestroy() {
        mIALocationManager.destroy();

        super.onDestroy();
    }

    @Override
    public void overridePendingTransition(int enterAnim, int exitAnim) {
        super.overridePendingTransition(enterAnim, exitAnim);
    }

    private IALocationListener mIALocationListener = new IALocationListener() {

        // Called when the location has changed.
        @Override
        public void onLocationChanged(IALocation location) {

            Log.d(TAG, "Latitude: " + location.getLatitude());
            Log.d(TAG, "Longitude: " + location.getLongitude());

            _result.setText("Latitude: " + location.getLatitude() + " Longitude: " + location.getLongitude());
        }

        @Override
        public void onStatusChanged(String s, int i, Bundle bundle) {
            _result.setText("Status: " + i);
        }
    };

    @Override
    public void onLocationChanged(Location location) {

        Log.d(TAG, "Latitude: " + location.getLatitude());
        Log.d(TAG, "Longitude: " + location.getLongitude());

        _result.setText("Latitude: " + location.getLatitude() + " Longitude: " + location.getLongitude());
    }

    @Override
    public void onStatusChanged(String provider, int status, Bundle extras) {

    }

    @Override
    public void onProviderEnabled(String provider) {

    }

    @Override
    public void onProviderDisabled(String provider) {

    }`

**Comment by GeekFreaker** [comment]
I'm having a similar problem, the onStatusChanged method is responding, but the location changed is not responding at all. Do I have to buy a Nexus 6 to program ?

**Comment by sai-cool** [comment]
I thought the same @GeekFreaker . I really have no idea on how it worked , but I have been trying on my Nexus9 for past 3 days... it is not working.

From the suggested devices on their website, I bought an Mi4 device.

First thing , we need to have the map generated from the floor plan. I got this generated only on the Mi4 device.

next, I think these didi the trick: The Permissions in the Manifest file are too critical.

I just copied these from this github’s AndroidManifest.xml and Pasted on my manifest file.

I tried fetching the floor plan on my Mi4.... still not working . After 2 minutes or so, I saw the map’s camera moving and ... wow it took me to the location of floor plan and loaded the map I generated on my Mi4 here. 


So, I think the permissions might be critical here. Now it is showing the floorplan on my Nexus 9 also .

**Comment by GeekFreaker** [comment]
`com.indooratlas.android.sdk.examples I/SensorManagerFlow: registerListenerImpl
                                                                                         java.lang.Exception
                                                                                             at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:118)
                                                                                             at android.hardware.SensorManager.registerListener(SensorManager.java:775)
                                                                                             at com.indooratlas.android.sdk._internal.cp.a(SourceFile:64)
                                                                                             at com.indooratlas.android.sdk._internal.ch.a(SourceFile:137)
                                                                                             at com.indooratlas.android.sdk._internal.bd.b(SourceFile:308)
                                                                                             at com.indooratlas.android.sdk._internal.av$b$d.d(SourceFile:4226)
                                                                                             at com.indooratlas.android.sdk._internal.av$b$j.a(SourceFile:1334)
                                                                                             at com.indooratlas.android.sdk._internal.ao$c.a(SourceFile:909)
                                                                                             at com.indooratlas.android.sdk._internal.ao$c.a(SourceFile:767)
                                                                                             at com.indooratlas.android.sdk._internal.ao$c.handleMessage(SourceFile:734)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)`

This is the error I'm getting I think that's my main issue.

**Comment by janpetryk** [comment]
I am getting the same bug in demo application: even though in log I get onStatusChanged: Available method onLocationChanged is not called when I move. I added my credentials to app, added a floor plan in indoor atlas webapp and use Nexus 5, still dont know what is going on.

**Comment by phonegap20** [comment]
Dear Team,
I am getting onStatusChanged: Available on console but onLocationChanged is not getting fired at all.
Calibration change. Quality: Excellent
Calibration change. Quality: Excellent
Calibration change. Quality: Excellent
Calibration change. Quality: Excellent
Calibration change. Quality: Poor
i can see all these messages but not location coordinates while i have GPS, WiFi on in my device.
Please resolve this problem and commit on repository so that we can implement it in app
Thanks a lot in advance !

**Comment by ntorppa** [comment]
Hi janpetryk & phonegap20, 
Have you used our MapCreator application to map the location first? If so, are you able to position with MapCreator in the same location?

Br,
Niko

**Comment by Nohemica** [comment]
Hi, 
I've used mapCreator and the mapping went well, I'm trying to make this example function with the map I uploaded, I used the Apy key and secret given to me but it won't work, is stays on: [000.82]: onStatusChanged: Available and nothing else.
The Image view and Location Sharing stays blank.

**Comment by elinapel** [comment]
Hi all,

Would you please sent the following information to support@indooratlas.com or start a chat from our [website](app.indooratlas.com):
-user account's e-mail
-used API-key and which floorplanID you're expecting to get
-which device (and os-version) was used to do the magnetic mapping of the venue

This will help us pinpoint the issue better and help your particular problem (it could be various reasons). Thanks!

Best regards,
Elina 
Customer Support

**Comment by phonegap20** [comment]
Hi ntorppa,

Thanks for your response.
I uploaded floor plan and mapped everything using Mapcreator app but still i am not getting any response.
only onStatusChanged: Available and besides that i am not getting anything.
I uploaded 2 floor plan to check it but this sdk sample does not provide any location.

Thanks,
Jitendra

**Comment by elinapel** [comment]
Hi phonegap20,

Please see my comment above for further troubleshooting. Thanks!

Elina

**Comment by jtgrassie** [comment]
Exactly same problem here. I get the status change but not location change.

**Comment by imilos** [comment]
Hi all, 

Have any of you solved this issue yet? I have exactly the same behavior on Nexus 5 (Android 6). 

Thanks in advance!

**Comment by jraanamo** [comment]
@imilos Assuming you have done mapping of some venue/floor plan where you are testing, did you try positioning with the MapCreator tool first and with what results?

**Comment by imilos** [comment]
I did mapping of the floor and MapCreator locates me correctly upon making 15-20 steps.

**Comment by jraanamo** [comment]
Have you tried looking at adb logcat output, does it print out any warnings with IASDK -tag?

**Comment by imilos** [comment]
@jraanamo 
E/IASDK: no permission to scan wifi. 

But the permissions are properly requested in the AndroidManifest.xml:

<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

**Comment by jraanamo** [comment]
If you are running on Android 6.0+ (?), then you need to request permission at runtime. In this case ACCESS_COARSE_LOCATION. See details here: https://developer.android.com/training/permissions/requesting.html.

**Comment by imilos** [comment]
You're right, it is Android 6.0. I performed the dynamic permission request but still getting:

`E/IASDK: no permission to scan wifi.`

Here is the list of permissions
![screenshot nov 14 2016 11-05-50 pm]
(https://cloud.githubusercontent.com/assets/8189900/20284837/34e755c8-aabf-11e6-901f-512f1b247a35.png)

Anything missing? Thanks a lot for your help!

**Comment by jraanamo** [comment]
Did you request and grant permissions **before** initialising IndoorAtlas SDK? Also, did you try running the SDK examples project as-is and did it work OK for you?

**Comment by imilos** [comment]
Hi @jraanamo, I realized that the problem was not with the permissions, but with map-id :(. Now it works like a charm. Thanks a lot for your help!

**Comment by jraanamo** [comment]
@imilos Great that you got it running. I will close this thread now, feel free to open more specific ones if you run into trouble.

**Comment by jtgrassie** [comment]
I have a floor plan and follow the instructions http://docs.indooratlas.com/android/dev-guide/getting-user-location.html but just never get location updates, only status which flips between 11 and 2.

**Comment by jraanamo** [comment]
@jtgrassie Are you trying to run example application as-is from this repository or code of your own?

**Comment by jtgrassie** [comment]
My own. No permissions errors or other errors. Just that the listener never gets location updates, only status.

**Comment by jraanamo** [comment]
Did you try with the example app and was the result any different?

**Comment by jtgrassie** [comment]
Same with your example app.

**Comment by jraanamo** [comment]
When you mapped the venue/floor plan with MapCreator app, did the
positioning work OK?

**Comment by jtgrassie** [comment]
Yes. I have a venue, with floorplan and lots of wayoints.

**Comment by jraanamo** [comment]
I think you have not created the magnetic map. For that you need to record data using the MapCreator tool and then generate the magnetic map from the data you have collected. This is described in more detail here: http://docs.indooratlas.com/app/. Once map is generated, you will see different kinds of visual analytics from your map in the webapp.

**Comment by jtgrassie** [comment]
"magnetic map"? First time I heard that phrase, cant find in the docs either. 
For clarity, I created an app, created venue, added floor plan, used MapCreator to create waypoints and then mapped location (recording). Is there another step??

**Comment by jraanamo** [comment]
Yes, you can record data several times before you actually choose to generate the map. Generating the map is described in the documentation on the page I mentioned above and illustrated in the screenshot below:

<img width="1137" alt="screen shot 2016-11-15 at 21 21 07" src="https://cloud.githubusercontent.com/assets/631747/20320209/c4fef322-ab79-11e6-9f5a-9a338fecf6d6.png">

The "creating of magnetic map" I referred to is actually a process that takes all raw sensor recordings collected and turns them into a format useable by the positioning algorithms. So this step is required before you can actually get any positions. The tool is designed so that you can review the collected data before you include them into the map being used. You can also exclude recorded paths if you feel they were not correct.

I agree that the documentation is not too clear and that there's multiple steps you need to carefully follow to successfully get positions. We'll revise this workflow and it's documentation to see how we can make it easier for developers to easily complete.

**Comment by jtgrassie** [comment]
Yes I have a **generated** map. Therefore have completed all steps. Still no location updates in either your demo simple app or my own.

**Comment by jraanamo** [comment]
@jtgrassie Yes, I can see that your map is now generated. Since resolving the remaining issues is very much specific to your data and settings, could I ask you to open a conversation via our customer support system from the https://app.indooratlas.com/.

**Comment by jtgrassie** [comment]
Sure. I'll reference this thread so I don't have to repeat myself! Though I'm not sure how specific it is to my 'data and settings' given many other people are having similar issues and that your very own example app is emitting the same issue.

**Comment by snehapantam** [comment]
has this issue solved? i am not getting any location updates sdk<6

**Comment by jraanamo** [comment]
@snehapantam We have no active issue open for not receiving location updates. It has always come down to mapping, device or setup related issue.

**Comment by adanali01** [comment]
After I install the map and generate map via indoor atlas map app I get notification from onLocationChanged. Does this mean that We must generate map to recieve location updates? Does anyone have idea?

**Comment by nbathras** [comment]
@adanali01 what exactly did you do to get the onLocationChanged.  I feel as if I have everything correctly configured and I have generated a map via indoor atlas mapp app but I still do not get any OnLocationChanged updates.

public class MainActivity extends AppCompatActivity {

    IALocationManager mLocationManager;

    private final int CODE_PERMISSIONS = 0;

    IALocationListener mLocationListener = new IALocationListener() {
        @Override
        public void onLocationChanged(IALocation iaLocation) {
            System.out.println("TEST1: ONLOCATIONCHANGED");
        }

        @Override
        public void onStatusChanged(String s, int i, Bundle bundle) {
            System.out.println("TEST1: ONSTATUSCHANGED");
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String[] neededPermissions = {
                Manifest.permission.CHANGE_WIFI_STATE,
                Manifest.permission.ACCESS_WIFI_STATE,
                Manifest.permission.ACCESS_COARSE_LOCATION
        };
        ActivityCompat.requestPermissions( this, neededPermissions, 3 );

        setContentView(R.layout.activity_main);

        mLocationManager = IALocationManager.create(this);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    protected void onResume() {
        super.onResume();
        mLocationManager.requestLocationUpdates(IALocationRequest.create(), mLocationListener);
    }

    @Override
    protected void onPause() {
        mLocationManager.removeLocationUpdates(mLocationListener);
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        mLocationManager.destroy();
        super.onDestroy();
    }
}

**Comment by adanali01** [comment]
Your code is similar to mine. But there is one difference about permissions. The problem might be requesting permissions. For the Android versions greater than 6.x.x, for my knowledge you should ask for the permissions even if you added them in the manifest. If this is not the case let me explain what i did step by step
1- I created a new location on web and added my floor plan via web api
2- In android app i selected my location and **made a record (with way points) then generated the map (Here is important you generate after recording)**
3- Added repositories and dependencies to gradle files (2 of the build.gradle files have changed)(I was confused about which of the _dependencies_ part should I add the dependency for Indoor. I added the code below) 
4- Added permissions and meta data(which is for API keys) to manifest
5- Changed the api keys in the manifest file 
6- Configured MainActivity
7- And of course you should be trying you app with the same location with you added on the web:)
I might have added extra permissions... (Mine is finding the distance you walk indoor)

# Here is my MainActivity

`package com.example.muhendis.indoorlocationfinder;

import android.Manifest;
import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.widget.TextView;

import com.indooratlas.android.sdk.IALocation;
import com.indooratlas.android.sdk.IALocationListener;
import com.indooratlas.android.sdk.IALocationManager;
import com.indooratlas.android.sdk.IALocationRequest;

public class MainActivity extends AppCompatActivity {

    private final int CODE_PERMISSIONS = 0;
    private IALocationManager mIALocationManager;
    private IALocationListener mIALocationListener;
    private String TAG="ONLOCATIONCHANGED";
    private TextView loc;
    private IALocation lastKnownLoc=null;
    private float distance=0;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String[] neededPermissions = {
                Manifest.permission.CHANGE_WIFI_STATE,
                Manifest.permission.ACCESS_WIFI_STATE,
                Manifest.permission.ACCESS_COARSE_LOCATION
        };
        ActivityCompat.requestPermissions( this, neededPermissions, CODE_PERMISSIONS );

      loc=(TextView)findViewById(R.id.loc);

        mIALocationManager = IALocationManager.create(this);


        mIALocationListener = new IALocationListener() {

            // Called when the location has changed.
            @Override
            public void onLocationChanged(IALocation location) {

                Log.d(TAG, "Latitude: " + location.getLatitude());
                Log.d(TAG, "Longitude: " + location.getLongitude());
                if(lastKnownLoc!=null)
                    distance+=lastKnownLoc.toLocation().distanceTo(location.toLocation());
                lastKnownLoc=location;
                loc.setText("Alınan Yol: "+distance);
                //loc.setText(loc.getText()+"\n"+"ON LOCATION CHANGED "+"Latitude: " + location.getLatitude()+" Longitude: " + location.getLongitude());
            }

            @Override
            public void onStatusChanged(String s, int i, Bundle bundle) {
                ////Log.d(TAG, "ONSTATUSCHANGED");
                //loc.setText(loc.getText()+"\n"+"ON STATUS CHANGED");
            }
        };

        mIALocationManager.requestLocationUpdates(IALocationRequest.create(),mIALocationListener);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);

        //Handle if any of the permissions are denied, in grantResults
        for (int result:grantResults
             ) {
            if(result!=0)
                loc.setText(loc.getText()+"\n"+"PERMISSION DENIED");
            else
                loc.setText(loc.getText()+"\n"+"PERMISSION GRANTED");

        }

    }

    @Override
    protected void onResume() {
        super.onResume();
        mIALocationManager.requestLocationUpdates(IALocationRequest.create(), mIALocationListener);
        loc.setText(loc.getText()+"\n"+"ON RESUME BASLADI");
        Log.d(TAG, "ONRESUME");
    }
    @Override
    protected void onPause() {
        super.onPause();
        mIALocationManager.removeLocationUpdates(mIALocationListener);
        loc.setText(loc.getText()+"\n"+"ON PAUSE BASLADI");
    }
}
`

# AndroidManifest

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.muhendis.indoorlocationfinder" >

    <uses-feature android:name="android.hardware.sensor.accelerometer"
        android:required="true" />
    <uses-feature android:name="android.hardware.sensor.compass"
        android:required="true" />
    <uses-feature android:name="android.hardware.sensor.gyroscope"
        android:required="true" />
    <uses-feature android:name="android.hardware.wifi"
        android:required="true" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme" >
        <activity android:name=".MainActivity" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <meta-data
            android:name="com.indooratlas.android.sdk.API_KEY"
            android:value="0a0a5a93-4a03-4d11..."/>
        <meta-data
            android:name="com.indooratlas.android.sdk.API_SECRET"
            android:value="2Ul7BUbzgeE6kZdNtvTJQBeeHLA6GdiPHp1d/vSab+c..."/>
    </application>

</manifest>`

# Build.gradle(Project: ...)

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "http://indooratlas-ltd.bintray.com/mvn-public"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

# Build.gradle(app)

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.muhendis.indoorlocationfinder"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    compile "com.indooratlas.android:indooratlas-android-sdk:2.4.1@aar"
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}
`

**Comment by adanali01** [comment]
@nbathras
