### ISSUE TITLE
Floor level is wrong in IALocation object even after hardcoding

### ISSUE THREAD

**Issue by ritikrishu** [IndoorAtlas/android-sdk-examples#51]
I am hard coding the floor plan in `IALocation` object, it should be floor level 3 but it is always showing 0.
this is the snnipet-
```
            mIALocationManager = IALocationManager.create(mContext);
            mIALocationManager.requestLocationUpdates(IALocationRequest.create(), this);
            mIALocationManager.registerRegionListener(this);
            mCurrentFloorPlan =  IARegion.floorPlan("<floor plan id>");
            mIALocationManager.setLocation(IALocation.from(mCurrentFloorPlan));
            Location targetLocation = new Location("");//provider name is unnecessary
            targetLocation.setLatitude(buildingLat);//your coords of course
            targetLocation.setLongitude(buildingLng);
            mIaLocation = IALocation.from(targetLocation);
```

**Comment by jraanamo** [comment]
So you are setting the floor plan explicitly because you somehow know that the user must always be in floor level 3? I don't quite understand from this code where/when is it that IndoorAtlas system returns floor level 0 when you expect 3?

**Comment by ritikrishu** [comment]
`mIaLocation.getFloorLevel()` was returning zero. We deleted the building from the dashboard and reconfigured. This issue is not coming anymore.

**Comment by ritikrishu** [comment]
@jraanamo not related to this issue, but can you tell me how to configure location scan intervals?
For example: I set the location request at 10 sec fastest interval and high priority, still getting location updates at ~90 sec intervals.
here is how my code looks-
```
IALocationRequest request = IALocationRequest.create()
                    .setFastestInterval(10000)
                    .setPriority(IALocationRequest.PRIORITY_HIGH_ACCURACY);
            mIALocationManager.requestLocationUpdates(request, this);
            mIALocationManager.registerRegionListener(this);
```

**Comment by jraanamo** [comment]
Once per 90 seconds is a really slow frequency. Is your use case  a foreground use case? Without setting any frequency you should expect to get update around 1-2 per second - that is, assuming your are walking.

**Comment by ritikrishu** [comment]
Yes, we are running a Foreground Service but it's other than the service implementing `IALocationListener`. We want to get location callbacks max at every thirty seconds regardless user activity is still or walking.
Do we need the service that implementing `IALocationListener` to run on the foreground?
How do we get guaranteed 30 sec locations for any device state?

**Comment by ritikrishu** [comment]
My foreground service(that keeps running even after app is closed) collects GPS locations and indoors locations indefinitely(in their own child services) until stopped explicitly. We get GPS locations continuously for hours, even if the device is kept still on a table. We need location per 30 sec, which GPS is giving but IndoorAtlas, however, gives location on larger delays.
When I walk around with the device in my hand, IndoorAtlas works as expected.
Also, the location callback frequency resumes to normal if I again pick the phone up and start walking.
The service implementation part looks quite right to me. I just want to know possibilities if Indoors will continue giving regular updates given the device is in absolute still position and screen locked for hours.
