### ISSUE TITLE
Is there any video tutorial as a guide to implement IndoorAtlas in android studio?

### ISSUE THREAD

**Issue by Aikahjmjm** [IndoorAtlas/android-sdk-examples#55]
Hi i am wondering if there is a video tutorial regarding this guide. I am confused on which code should i implement in AS. Also, does this guide include the codes for the polylines too?

**Comment by oseiskar** [comment]
Unfortunately we don not  have an up-to-date video tutorial for Android Studio. Regarding polylines, there is an example how they can be used to visualize wayfinding routes here https://github.com/IndoorAtlas/android-sdk-examples/blob/582085f56f7e3f100a1c4cc2211facf4e7e70fbe/Basic/src/main/java/com/indooratlas/android/sdk/examples/wayfinding/WayfindingOverlayActivity.java#L512-L536
