### ISSUE TITLE
Distace between two location

### ISSUE THREAD

**Issue by faizyfaazz** [IndoorAtlas/android-sdk-examples#59]
Hi,
I use Indoor atlas SDK for get people visiting area analysis(Heat map creation). i store the latitude and longitude of the user in my database.
My problems are:
(1)  I placed my phone in a table(phone in a idle state) and when open the application,the onLocationChanged(IALocation location) calls around 21 times .why this happen? why is it calling these much times without any movement ?

(2) Can i get location update within 10 Meter displacement interval.

**Comment by oseiskar** [comment]
Hi! The thing you are looking for is the _distance filter_, which is available, but not enabled by default. To use it you have to [`setSmallestDisplacement` in `IALocationRequest`](https://docs.indooratlas.com/android/latest/com/indooratlas/android/sdk/ialocationrequest). The ["Simple" SDK example](https://github.com/IndoorAtlas/android-sdk-examples/blob/4fd8735c1058b1a41567d6b303eca3b650cba908/Basic/src/main/java/com/indooratlas/android/sdk/examples/simple/SimpleActivity.java) also demonstrates how to use this feature.
