### ISSUE TITLE
Wayfinding issue

### ISSUE THREAD

**Issue by abhinavgitaccount** [IndoorAtlas/android-sdk-examples#62]
Exporting Wayfinding-graph.json dosn't seems to be providing correct file

I can see only below lines in my json which is causing build error
{"nodes":[],"edges":[]}

Is wayfinding feature not yet available

**Comment by oseiskar** [comment]
That is strange. Did you first draw and save the wayfinding graph as instructed [on this help page](https://indooratlas.freshdesk.com/support/solutions/articles/36000051250-creating-the-wayfinding-graph)?

I also strongly recommend you to upgrade to Android SDK 2.9, where you do not need to manually download the wayfinding graph anymore. See https://indooratlas.freshdesk.com/support/solutions/articles/36000085136-migrating-to-android-sdk-2-9/preview#wayfinding and https://indooratlas.freshdesk.com/support/solutions/articles/36000095621-using-wayfinding-with-android
