### ISSUE TITLE
location sharing example not working

### ISSUE THREAD

**Issue by greedyshardul** [IndoorAtlas/android-sdk-examples#63]
Opening 05.location sharing causes app to crash. Do i have to create pubnub account and add my own keys?

**Comment by mippe** [comment]
Seems this was likely fixed in : https://github.com/IndoorAtlas/android-sdk-examples/commit/0481e1b356daa6b6dcdc94b69e33f279c8a745fe#diff-19a73ecb5b6799489c9fdccf7b46d693

Sorry about the delay in notifying.
