### ISSUE TITLE
Demo app not working on Vuzix M300

### ISSUE THREAD

**Issue by jorenjamar** [IndoorAtlas/android-sdk-examples#68]
I am trying to run the demoapp on a Vuzix M300. If you look at the documentation of the Vuzix, you can see that it has a magnetometer, gyroscope and accelerometer. If I run the simple demo on the Vuzix, I get the quality but I do not get the actual location. There is an error .
`E/IACore: Cannot lock/unlock floor after setLocation`
If I run the app on my Samsung S9, it works. Does anyone know what the problem is? You can find the documentation of the Vuzix M300 here https://www.vuzix.com/Products/m300-smart-glasses/#/m300-texhnical-specs

**Comment by oseiskar** [comment]
Non-phone devices are not currently officially supported by the full IndoorAtlas SDK. The only offically supported mechanism for running positioning on embedded devices is the [positioning API](https://indooratlas.freshdesk.com/support/solutions/articles/36000051260-positioning-rest-api-overview).

However, you may try SDK version 2.8 (e.g., this commit https://github.com/IndoorAtlas/android-sdk-examples/commit/582085f56f7e3f100a1c4cc2211facf4e7e70fbe in this repository). It runs on a smartwatch with minimal modifications (https://github.com/IndoorAtlas/android-sdk-examples/commits/smartwatch-28).

Also first verify that positioning works on a phone to eliminate other potential issues.
