### ISSUE TITLE
Nothing works on Samsung A5, Android 6.0.1

### ISSUE THREAD

**Issue by madani2010** [IndoorAtlas/android-sdk-examples#71]
Hi,

I am trying to run the android samples but nothing seems to work.The imageview example shows white screen.The google maps basic sample shows a google map with nothing on it.The same for google maps overlay and openstreetmaps.
I have already created an application with floor plan and waypoints on atlas web app.

My device is Samsung A5, Android V 6.0.1.

Thanks

Madani

**Comment by oseiskar** [comment]
Hi Madani. IndoorAtlas positioning works after you have [fingerprinted the venue](https://indooratlas.freshdesk.com/support/solutions/articles/36000103986-fingerprinting-overview), which involves walking around the premises, recording data with the IndoorAtlas Map Creator 2 application. You can find more help and info about fingerprinting at https://support.indooratlas.com
