### ISSUE TITLE
ImageView Example displays nothing

### ISSUE THREAD

**Issue by fire-walkwithme** [IndoorAtlas/android-sdk-examples#74]
Hello.

I tried to run the ImageView example but the floor map and the blue dot are not displayed, although I use the application in the mapped area.
https://imgur.com/a/nsJ1R0J
I added a location and mapped it with Map Creator. I created an application and configured the API keys in gradle.properties and in strings.xml.

I don't know what to try anymore.

Thank you.

**Comment by oseiskar** [comment]
Please report issues related to deploying IndoorAtlas positioning in the [support portal](https://https://support.indooratlas.com): First go through the [troubleshooting section](https://indooratlas.freshdesk.com/support/solutions/articles/36000050553-troubleshooting-positioning-overview) and, if this does not resolve the issue, then create a ticket. Also make sure to include your username and details about the test device.
