### ISSUE TITLE
Preview image not according to layout file

### ISSUE THREAD

**Issue by MartinPessoa** [IndoorAtlas/android-sdk-examples#78]
Hello, 

I'm trying to port this test to my xamarin.forms application. However, I noticed what i think might be an outdated image in readme.md. The image shows 3 buttons on the bottom, "Request Updates", "Remove Updates", and "Set Location". See it in this link:

Image link: https://github.com/IndoorAtlas/android-sdk-examples/raw/master/example-screenshots/simple_01.jpg

Now, when looking at the layout source code, there's only two buttons "Request" and "Remove" Updates, there's no "Set Location".

Layout: https://github.com/IndoorAtlas/android-sdk-examples/blob/master/Basic/src/main/res/layout/activity_simple.xml

This is something minor, but since i'm am having some trouble running this example in xamarin forms, I wanted to report it so I can rule out that my code is not running because the code for that "Set Location" button is missing from your code, or if the image in readme.md is just outdated and my code should be running as it is (copied and translated to C# from your code).

**Comment by oseiskar** [comment]
Hi. You are right, that the image is outdated. The _Set Location_ button was removed when that functionality was deprecated in SDK 3.0.
