### ISSUE TITLE
do i need beacon to create direction on my indoor map ?

### ISSUE THREAD

**Issue by ztuning** [IndoorAtlas/android-sdk-examples#82]
because another indoor SDK need beacon :(
i hope its not, thanks

**Comment by matti-ida** [comment]
Hi,

beacons are required for iOS support, but not strictly required on Android (though recommended).

See our support portal for more info:
https://indooratlas.freshdesk.com/support/home
https://indooratlas.freshdesk.com/support/solutions/articles/36000050501-why-to-use-beacons-with-indooratlas-
https://indooratlas.freshdesk.com/support/solutions/articles/36000112563-android-9-wifi-fingerprinting-limitations
